Repository nasa/LC, pull requests merged in 2022-06, with the labels that each got.

#31 Fix #20 #25, Add requirements rationale and clarify event message limit requirement
  docs/lc_FunctionalRequirements.csv
Labels: CCB:Approved

#33 Fix #32, Remove CFE_PSP_MemSet use for addresses in RAM
  fsw/src/lc_app.c
  fsw/src/lc_watch.c
  unit-test/lc_app_tests.c
  unit-test/utilities/lc_test_utils.c
Labels: CCB:Approved

#35 Fix #34, Updates CLA information for Apache 2.0
  .github/pull_request_template.md
  CONTRIBUTING.md
  docs/Corp_CLA_LC_220.pdf
  docs/Indv_CLA_LC_220.pdf
Labels: docs, CCB:Approved

#30 Fix #29, Added codeql-build.yml
  .github/workflows/codeql-build.yml
Labels: CCB:Approved, dependency
